"""role title upg

Revision ID: 317ee5b85208
Revises: 06aaff81614a
Create Date: 2023-06-22 18:41:28.323991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317ee5b85208'
down_revision = '06aaff81614a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_title', table_name='role')
    op.create_index(op.f('ix_role_title'), 'role', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_title'), table_name='role')
    op.create_index('ix_role_title', 'role', ['title'], unique=False)
    # ### end Alembic commands ###
