"""add utc suffix

Revision ID: ed626abebd08
Revises: 673ef283f32b
Create Date: 2023-06-23 13:36:17.855637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed626abebd08'
down_revision = '673ef283f32b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('signed_at_utc', sa.TIMESTAMP(), nullable=True))
    op.add_column('employee', sa.Column('last_promotion_utc', sa.TIMESTAMP(), nullable=True))
    op.add_column('employee', sa.Column('next_promotion_utc', sa.TIMESTAMP(), nullable=True))
    op.drop_index('ix_employee_signed_at', table_name='employee')
    op.create_index(op.f('ix_employee_signed_at_utc'), 'employee', ['signed_at_utc'], unique=False)
    op.drop_column('employee', 'next_promotion')
    op.drop_column('employee', 'last_promotion')
    op.drop_column('employee', 'signed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('last_promotion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('next_promotion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employee_signed_at_utc'), table_name='employee')
    op.create_index('ix_employee_signed_at', 'employee', ['signed_at'], unique=False)
    op.drop_column('employee', 'next_promotion_utc')
    op.drop_column('employee', 'last_promotion_utc')
    op.drop_column('employee', 'signed_at_utc')
    # ### end Alembic commands ###
