"""change datetime -> str 2

Revision ID: 6aa6b2113e88
Revises: 4b2ed31646fb
Create Date: 2023-06-23 13:16:25.778536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aa6b2113e88'
down_revision = '4b2ed31646fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'signed_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('employee', 'last_promotion',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('employee', 'next_promotion',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'next_promotion',
                    existing_type=sa.String(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('employee', 'last_promotion',
                    existing_type=sa.String(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('employee', 'signed_at',
                    existing_type=sa.String(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    # ### end Alembic commands ###
