"""remove role tables 2

Revision ID: bcc4bb85ad16
Revises: 6d14e7c8e1ff
Create Date: 2023-06-23 10:09:50.173456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc4bb85ad16'
down_revision = '6d14e7c8e1ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_role_id', table_name='employee')
    op.drop_constraint('employee_role_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('employee_role_id_fkey', 'employee', 'role', ['role_id'], ['id'])
    op.create_index('ix_employee_role_id', 'employee', ['role_id'], unique=False)
    # ### end Alembic commands ###
