"""change str -> datetime

Revision ID: 673ef283f32b
Revises: 6aa6b2113e88
Create Date: 2023-06-23 13:24:18.611143

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '673ef283f32b'
down_revision = '6aa6b2113e88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'signed_at',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('employee', 'last_promotion',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('employee', 'next_promotion',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TIMESTAMP(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'next_promotion',
                    existing_type=sa.TIMESTAMP(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.alter_column('employee', 'last_promotion',
                    existing_type=sa.TIMESTAMP(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.alter_column('employee', 'signed_at',
                    existing_type=sa.TIMESTAMP(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
