"""role perm update

Revision ID: 06aaff81614a
Revises: a8f927a55329
Create Date: 2023-06-22 18:40:18.251440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aaff81614a'
down_revision = 'a8f927a55329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
