"""add unique flag to username

Revision ID: 6c054202a874
Revises: ed626abebd08
Create Date: 2023-06-23 20:43:47.095749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c054202a874'
down_revision = 'ed626abebd08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_username', table_name='employee')
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.create_index('ix_employee_username', 'employee', ['username'], unique=False)
    # ### end Alembic commands ###
