"""change datetime -> str

Revision ID: 4b2ed31646fb
Revises: d94d0bdf9908
Create Date: 2023-06-23 13:09:57.881151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2ed31646fb'
down_revision = 'd94d0bdf9908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
