"""add employee date's

Revision ID: 0845a394ba0e
Revises: 61f5e8b21691
Create Date: 2023-06-22 13:20:30.770686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0845a394ba0e'
down_revision = '61f5e8b21691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('signed_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('employee', sa.Column('last_promotion', sa.TIMESTAMP(), nullable=False))
    op.add_column('employee', sa.Column('next_promotion', sa.TIMESTAMP(), nullable=False))
    op.create_index(op.f('ix_employee_signed_at'), 'employee', ['signed_at'], unique=False)
    op.add_column('job', sa.Column('salary', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_job_salary'), 'job', ['salary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_salary'), table_name='job')
    op.drop_column('job', 'salary')
    op.drop_index(op.f('ix_employee_signed_at'), table_name='employee')
    op.drop_column('employee', 'next_promotion')
    op.drop_column('employee', 'last_promotion')
    op.drop_column('employee', 'signed_at')
    # ### end Alembic commands ###
