"""uncomment date columns in emp

Revision ID: d94d0bdf9908
Revises: bcc4bb85ad16
Create Date: 2023-06-23 11:28:11.963437

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd94d0bdf9908'
down_revision = 'bcc4bb85ad16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_role_title'), 'role', ['title'], unique=True)
    op.add_column('employee', sa.Column('signed_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('employee', sa.Column('last_promotion', sa.TIMESTAMP(), nullable=True))
    op.add_column('employee', sa.Column('next_promotion', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_employee_signed_at'), 'employee', ['signed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_signed_at'), table_name='employee')
    op.drop_column('employee', 'next_promotion')
    op.drop_column('employee', 'last_promotion')
    op.drop_column('employee', 'signed_at')
    op.drop_index(op.f('ix_role_title'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
