"""remove role tables

Revision ID: 6d14e7c8e1ff
Revises: 126beff21185
Create Date: 2023-06-23 10:06:51.346319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d14e7c8e1ff'
down_revision = '126beff21185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
