"""initial migration

Revision ID: 61f5e8b21691
Revises: 
Create Date: 2023-06-22 12:58:58.298897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f5e8b21691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False, comment="example: [perm1, perm2, perm3]. All perm's is string"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_title'), 'role', ['title'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_firstname'), 'employee', ['firstname'], unique=False)
    op.create_index(op.f('ix_employee_job_id'), 'employee', ['job_id'], unique=False)
    op.create_index(op.f('ix_employee_lastname'), 'employee', ['lastname'], unique=False)
    op.create_index(op.f('ix_employee_role_id'), 'employee', ['role_id'], unique=False)
    op.create_index(op.f('ix_employee_username'), 'employee', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_username'), table_name='employee')
    op.drop_index(op.f('ix_employee_role_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_lastname'), table_name='employee')
    op.drop_index(op.f('ix_employee_job_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_firstname'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_role_title'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
